version: "3.7"
services:
  server:
    image: ylihallila/openmicroanatomy-server:latest
    restart: always
    ports:
      # Change to "127.0.0.1:7777:7777" after enabling Reverse Proxy (see docs) to prevent insecure connections using HTTP.
      - "7777:7777"
    volumes:
      - ./server-data:/home/oma/server
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=90.0
